config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  
 resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Books#edit</h1>

app/views/books/index.html.erb
<h1>Books#index</h1>

app/views/books/show.html.erb
<h1>Books#show</h1>

app/views/homes/top.html.erb
<body>
 <h1>
  ようこそ<strong>Bookers</storng>へ！
 </h1>

<span>
  Bookersは、さまざまな書籍に対するあなたの意見や印象を、<br />
  投稿し、共有することができます。<br />
  </span>


   <%= link_to "Start",books_path,class:"btn btn-outline btn-block" %>

</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers12</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>